PINECONE_API_KEY = "pcsk_9coPz_9U1G4VhXwbfPKYapvRGdXQhCBMhxU7LYwbZny8g5hGmemT7pUGaj3ZV6gKFwaWF"
OPENAI_API_KEY = "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"
MONGO_URI = "mongodb+srv://dorianmarty:Marty2024!@clustergdp.mq5yk.mongodb.net/?retryWrites=true&w=majority&appName=ClusterGDP"
